name: cloud-scraping-api

services:

  web:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - ./:/code:ro
    environment:
      - "postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${PORT}/${POSTGRES_DB}"
    env_file:
      - .env 

  db:
    image: postgres
    ports: 
      - ${PORT}:${PORT}
    expose:
      - ${PORT}
    env_file:
      - .env 
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    command: -p ${PORT}

volumes:
      postgres_data: 
  