name: cloud-scraping-api

services:

  web:
    image: rafaeldbo/scraping-api
    ports:
      - ${API_PORT}:8080
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${DB_PORT}/${POSTGRES_DB}"
    env_file:
      - .env 

  db:
    image: postgres
    expose:
      - ${DB_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    command: -p ${DB_PORT}
    env_file:
      - .env 

volumes:
      postgres_data: 
  